repos:
-   repo: local
    hooks:
    -   id: style_enforcement
        name: style_enforcement
        stages: [commit]
        language: system
        entry: scripts/style_enforcement.sh
        always_run: true
        pass_filenames: false

    -   id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: pytest . -q
        always_run: true
        pass_filenames: false

    -   id: pytest-cov
        name: pytest-cov
        stages: [push]
        language: system
        entry: pytest --cov --cov-fail-under=95
        types: [python]
        pass_filenames: false